# -*- coding: utf-8 -*-
"""Desafios_aula 01.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jl8UeR_-N9n4zTcKYeD5GHLAmVQmI0Fi

# Desafio 1
"""

selecao = filmes_com_media['nota'].isnull()
filmes_com_media[selecao]

"""# Desafio 2"""

filmes_com_media = filmes_com_media.rename(columns={'nota': 'nota_media'})
filmes_com_media.head()

"""# Desafio 3"""

total_votos_por_filme = avaliacoes.groupby('filmeId')['nota'].count()
total_votos_por_filme.head()

filmes_com_media_e_votos = filmes_com_media.join(total_votos_por_filme, on='filmeId')
filmes_com_media_e_votos = filmes_com_media_e_votos.rename(columns={'nota': 'total_votos'})
filmes_com_media_e_votos.head()

"""# Desafio 4"""

filmes_com_media_e_votos['nota_media'] = filmes_com_media_e_votos['nota_media'].round(2)
filmes_com_media_e_votos

"""# Desafio 5"""

generos_df = filmes_com_media_e_votos.generos.str.get_dummies('|')
generos = generos_df.columns.to_list()
generos

"""# Desafio 6"""

total_filmes_por_genero = filmes_com_media_e_votos.generos.str.get_dummies().sum()
total_filmes_por_genero

"""# Desafio 7"""

total_filmes_por_genero.sort_values(ascending=False).plot(kind='bar', figsize=(16, 6))